samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Models/ErrorViewModel.cs
using System;

namespace movierecommender.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Models/Movie.cs
namespace movierecommender.Models
{
    public class Movie
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }

        public bool liked;
    }
}

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Models/Profile.cs
using System.Collections.Generic;

namespace movierecommender.Models
{
    public class Profile
    {
        public int ProfileID { get; set; }
        public string ProfileImageName { get; set;}
        public string ProfileName { get; set; }
        public List<(int movieId, int movieRating)> ProfileMovieRatings { get; set;}
     }
}

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ML;
using Microsoft.Extensions.Options;
using Microsoft.ML;
using movierecommender.Models;
using movierecommender.Services;
using MovieRecommender.DataStructures;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;

namespace movierecommender.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IProfileService _profileService;
        private readonly AppSettings _appSettings;
        private readonly ILogger<MoviesController> _logger;
        private readonly PredictionEnginePool<MovieRating, MovieRatingPrediction> _model;

        public MoviesController(PredictionEnginePool<MovieRating, MovieRatingPrediction> model,
            ILogger<MoviesController> logger,
            IOptions<AppSettings> appSettings,
            IMovieService movieService,
            IProfileService profileService)
        {
            _movieService = movieService;
            _profileService = profileService;
            _logger = logger;
            _appSettings = appSettings.Value;
            _model = model;
        }

        public ActionResult Choose()
        {
            return View(_movieService.GetSomeSuggestions());
        }

        public ActionResult Recommend(int id)
        {
            var activeprofile = _profileService.GetProfileByID(id);

            // 1. Create the ML.NET environment and load the already trained model
            MLContext mlContext = new MLContext();

            List<(int movieId, float normalizedScore)> ratings = new List<(int movieId, float normalizedScore)>();
            var MovieRatings = _profileService.GetProfileWatchedMovies(id);
            List<Movie> WatchedMovies = new List<Movie>();

            foreach ((int movieId, int movieRating) in MovieRatings)
            {
                WatchedMovies.Add(_movieService.Get(movieId));
            }
                        
            MovieRatingPrediction prediction = null;
            foreach (var movie in _movieService.GetTrendingMovies)
            {
                // Call the Rating Prediction for each movie prediction
                 prediction = _model.Predict(new MovieRating
                 {
                     userId = id.ToString(),
                     movieId = movie.MovieID.ToString()
                 });

                // Normalize the prediction scores for the "ratings" b/w 0 - 100
                float normalizedscore = Sigmoid(prediction.Score);

                // Add the score for recommendation of each movie in the trending movie list
                 ratings.Add((movie.MovieID, normalizedscore));
            }

            //3. Provide rating predictions to the view to be displayed
            ViewData["watchedmovies"] = WatchedMovies;
            ViewData["ratings"] = ratings;
            ViewData["trendingmovies"] = _movieService.GetTrendingMovies;
            return View(activeprofile);
        }

        public float Sigmoid(float x)
        {
            return (float) (100/(1 + Math.Exp(-x)));
        }

        public ActionResult Watch()
        {
            return View();
        }

        public ActionResult Profiles()
        {
            var profiles = _profileService.GetProfiles;
            return View(profiles);
        }

        public ActionResult Watched(int id)
        {
            var activeprofile = _profileService.GetProfileByID(id);
            var MovieRatings = _profileService.GetProfileWatchedMovies(id);
            List<Movie> WatchedMovies = new List<Movie>();

            foreach ((int movieId, float normalizedScore) in MovieRatings)
            {
                WatchedMovies.Add(_movieService.Get(movieId));
            }

            ViewData["watchedmovies"] = WatchedMovies;
            ViewData["trendingmovies"] = _movieService.GetTrendingMovies;
            return View(activeprofile);
        }

        public class JsonContent : StringContent
        {
            public JsonContent(object obj) :
                base(JsonConvert.SerializeObject(obj), Encoding.UTF8, "application/json")
            { }
        }
    }
}

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Choose.cshtml
@using movierecommender.Models
@model IEnumerable<Movie>
@{
    ViewBag.Title = "Choose";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>

<h3>Pick the movie you best liked in the past?</h3>

<div class="row">
    @foreach (var movie in Model)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-block">
                    <h3 class="card-title">@movie.MovieName</h3>
                    <a href="@Url.Action("Recommend", "Movies", new { id = movie.MovieID })" class="btn btn-primary">Choose me</a>
                </div>
            </div>
        </div>
    }
</div>

<hr />
<div class="form-row">
    <button type="button" class="btn btn-info" id="select" onclick="location.href='@Url.Action("Choose", "Movies")'">
        <span class="glyphicon glyphicon-ok"></span> Recommend Movies
    </button>
</div>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Profiles.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using movierecommender.Models
@model IEnumerable<Profile>
@{
}

<h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>
<hr />
<h3>Who's watching?</h3>
<br />

<div class="row">
    @foreach (var profile in Model)
    {
        <div class="col-sm-3">
            <div class="card">
                <div class="card-block">
                    <img src="~/images/@profile.ProfileImageName" width="100" height="100" align="bottom" class="img-circle" />
                    <br /> <br>
                    <a href="@Url.Action("Watched", "Movies", new { id = profile.ProfileID })" style="font-size:26px" class="card-title">@profile.ProfileName</a>
                </div>
            </div>
        </div>
    }
</div>
<br />
<br />
<hr />
<button type="button" class="btn breadcrumb">
    <span class="glyphicon glyphicon-dashboard"></span> Manage Profiles
</button>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Recommend.cshtml
@using movierecommender.Models
@model Profile
@{
    ViewBag.Title = "Recommend";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Profile profile = Model;
    var WatchedMovie = (List<Movie>)ViewData["watchedmovies"];
    var MovieRatings = (List<(int movieId, float score)>) ViewData["ratings"];
    var TrendingMovie = (List<Movie>)ViewData["trendingmovies"];
}
<div class="row">
    <div class="col-sm-9">

        <h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>
    </div>

    <div class="col-sm-3">
        <img src="~/images/@profile.ProfileImageName" width="50" height="50" align="bottom" class="img-rounded" title="@profile.ProfileName profile" />
        <h4> @profile.ProfileName </h4>
    </div>
</div>
<hr />

<br />
<h3 style="color:brown"><b>Your Recently Watched Movies</h3>
<div class="row">
    @foreach (var movie in WatchedMovie)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-block">
                    <h3 class="card-title">@movie.MovieName</h3>
                    @{
                        bool thumbsup = false;
                        foreach ((int movieId, int movieRating) in profile.ProfileMovieRatings)
                        {
                            if (movieId == movie.MovieID)
                            {
                                if (movieRating >= 4)
                                {
                                    thumbsup = true;
                                    break;
                                }
                            }
                        }
                    }

                    @if (thumbsup)
                    {
                        <span class="glyphicon glyphicon-thumbs-up" />
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-thumbs-down" />
                    }
                    <a href="@Url.Action("Watch", "Movies")" class="btn-xs btn-primary">Watch Again</a>
                </div>
            </div>
        </div>
    }
</div>

<hr />
<h3 style="color:brown"><b>All-Time Top Box-Office movies (Recommended)</h3>
<div class="row">
    @foreach (var movie in TrendingMovie)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-block">
                    <h3 class="card-title">@movie.MovieName</h3>
                    @{
                        foreach ((int movieId, float normalizedScore) in MovieRatings)
                        {
                            if (movieId == movie.MovieID)
                            {

                                var formatted = normalizedScore.ToString("0.##\\%");
                                <span class="glyphicon glyphicon-fire"></span>@formatted;
                            }
                        }
                    }
                    <a href="@Url.Action("Watch", "Movies")" class="btn-xs btn-primary">Play Movie</a>
                </div>
            </div>
        </div>
    }
</div>
<br />
<hr />
<button type="button" class="btn breadcrumb" id="select" onclick="location.href='@Url.Action("Recommend", "Movies", new {id = profile.ProfileID})'">
    <span class="glyphicon glyphicon-fire"></span> Recommended
</button>
<button type="button" class="btn breadcrumb" id="select" onclick="location.href='@Url.Action("Profiles", "Movies")'">
    <span class="glyphicon glyphicon-dashboard"></span> Switch Profiles
</button>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Recommendations.cshtml
@using movierecommender.Models
@model IEnumerable<Movie>
@{
    ViewBag.Title = "Recommendations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>

<hr>
<h3>Trending Movies</h3>

<div class="row">
    @if (Model != null)
    {
        foreach (var movie in Model)
        {
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-block">
                        <h3 class="card-title">@movie.MovieName</h3>
                        <a href="@Url.Action("Watch", "Movies")" class="btn btn-primary">Play Movie</a>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <h2>Something went wrong! please check the error log.</h2>
    }
</div>
<hr />
<button type="button" class="btn breadcrumb" id="select" onclick="location.href='@Url.Action("Profiles", "Movies")'">
    <span class="glyphicon glyphicon-ok "></span> This is fun, let me try again!
</button>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Watch.cshtml
@{
    ViewBag.Title = "Watch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>

<h1>That's as far as this gets today!</h1>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Movies/Watched.cshtml
@using movierecommender.Models
@model Profile
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    Profile profile = Model;
    var WatchedMovie = (List<Movie>)ViewData["watchedmovies"];

}


<div class="row">
    <div class="col-sm-9">

        <h1><span class="glyphicon glyphicon-film"></span> Movie Recommender</h1>
    </div>

    <div class="col-sm-3">
        <img src="~/images/@profile.ProfileImageName" width="50" height="50" align="bottom" class="img-rounded" title="@profile.ProfileName profile" />
        <h4> @profile.ProfileName </h4>
    </div>
</div>
<hr />

<br />
<h3 style="color:brown"><b>Your Recently Watched Movies</h3>
<div class="row">
    @foreach (var movie in WatchedMovie)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-block">
                    <h3 class="card-title">@movie.MovieName</h3>
                    @{
                        bool thumbsup = false;
                        foreach ((int movieId, int movieRating) in profile.ProfileMovieRatings)
                        {
                            if (movieId == movie.MovieID)
                            {
                                if (movieRating >= 4)
                                {
                                    thumbsup = true;
                                    break;
                                }
                            }
                        }
                    }

                    @if (thumbsup)
                    {
                        <span class="glyphicon glyphicon-thumbs-up" />
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-thumbs-down" />
                    }
                    <a href="@Url.Action("Watch", "Movies")" class="btn-xs btn-primary">Watch Again</a>
                </div>
            </div>
        </div>
    }
</div>

<hr />
<h3 style="color:brown"><b>All-Time Top Box-Office movies</h3>
<div class="row">
    @{
        var TrendingMovie = (List<Movie>)ViewData["trendingmovies"];
    }
    @foreach (var movie in TrendingMovie)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-block">
                    <h3 class="card-title">@movie.MovieName</h3>
                    <a href="@Url.Action("Watch", "Movies")" class="btn-xs btn-primary">Play Movie</a>
                </div>
            </div>
        </div>
    }
</div>
<br />
<hr />
<button type="button" class="btn breadcrumb" id="select" onclick="location.href='@Url.Action("Recommend", "Movies", new {id = profile.ProfileID})'">
    <span class="glyphicon glyphicon-fire"></span> Recommended
</button>
<button type="button" class="btn breadcrumb" id="select" onclick="location.href='@Url.Action("Profiles", "Movies")'">
    <span class="glyphicon glyphicon-dashboard"></span> Switch Profiles
</button>

samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender/movierecommender/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - movierecommender</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
      <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - movierecommender</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>